name: nova
description: "'NOVA' is a store application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  fluttertoast: ^8.2.12
  get_it: ^8.2.0
  go_router: ^16.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart

flutter_native_splash:
  color: '#FFFCF2'
  image: assets/images/nova.png
flutter_intl:
  enabled: true
